title: Project
pages: false
files: true
  fields:
    caption:
      label: Caption
      type: textarea
fields:
  title:
    label: Title
    type:  text
  category:
    label: Category
    type: select
    required: true
    options:
      furniture: Furniture
      remodel: Remodel
      featured: Mixed
    help:  Choose the right category to help people sort photos using the filter bar on the homepage. The "mixed" category gets excluded from filter results.

