title: Project
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  category:
    label: Category
    type: select
    required: true
    options:
      furniture: Furniture
      remodel: Remodel
  woods:
    label: Wood Types
    type:  tags
    index: siblings
    lower: true

