title: Project
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  category:
    label: Category
    type: select
    required: true
    width: 1/2
    options:
      furniture: Furniture
      remodel: Remodel
    help:  Choose the right category to help people sort photos using the filter bar on the homepage.
  woods:
    label: Wood Types
    type:  tags
    index: siblings
    lower: true
    width: 1/2

