title: Site
pages: default
fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  text
    icon:  quote-
  name:
    label: Name
    type:  text
    default: John E. Decker
    width: 1/2
  jobTitle:
    label: Job Title
    type:  text
    default: Craftsman
    width: 1/2
  phone:
    label: Phone
    type:  tel
    default: (828) 808-2116
    width: 1/2
  email:
    label: Email
    type:  email
    default: john@rightanglewoodworks.com
    width: 1/2
  copyright:
    label: Copyright
    type:  text
    icon:  copyright
